# These options apply to how the script will operate.
script_options:
  LANGUAGE: 'es'
  # Switch between testnet and mainnet
  # Setting this to False will use REAL funds, use at your own risk
  #MODES: (ONLINE, ONLINETESNET), (TESTMODE, BACKTESTING)
  MODE: "BACKTESTING"
  BOT_TIMEFRAME: "1m"
  BACKTESTING_MODE_TIME_START: "01/01/22  00:00:00"
  BACKTESTING_MODE_TIME_END: "31/12/22 00:00:00" 
  LOG_TRADES: True
  JSON_REPORT: 'report.json'
  MICROSECONDS: 0.3
  LOG_FILE: 'log.txt'
  TRADES_LOG_FILE: 'trades.csv'
  TRADES_GRAPH: 'graphics.html'
  TRADES_INDICATORS: 'indicator.csv'
  #USE_TRADES_INDICATORS: False
  FILE_SYMBOL_INFO: 'symbol.info'
  #if it is empty no information will be saved
  #HISTORY_LOG_FILE: '' #'history.html'
  COINS_BOUGHT: 'coins_bought.json'
  BOT_STATS: 'bot_stats.json'
  PRINT_TABLE_COMMISSIONS: False
  USE_VOLATILE_METOD: False
  DEBUG: True
  SILENT_MODE: True
  #through telnet it is possible to obtain the value of this or that variable in a function
  REMOTE_INSPECTOR_BOT_PORT: 0 #9998
  #if 0 remote server is disabled
  REMOTE_INSPECTOR_MEGATRONMOD_PORT: 0 #9999
  #all binance requests from our bot will be proxied
  PROXY_HTTP: '' #'http://localhost:8090'
  PROXY_HTTPS: ''
  # Set this to true if you are accessing binance from within the United States of America
  # Need to change TLD
  AMERICAN_USER: False
  BUY_PAUSED: False

# These options apply to the trading methods the script executes
trading_options: 
  # select your base currency to use for trading (trade for example USDT pairs)
  PAIR_WITH: USDT #FDUSD  
  #When activating this option, as long as the TRADE_SLOTS option is 1, 
  #it will be bought with all the capital in the wallet.
  #The method works....
  COMPOUND_INTEREST: False
  # Total amount per trade (your base currency balance must be at least TRADE_SLOTS * TRADE_TOTAL)
  # Binance uses a minimum of 10 USDT per trade, add a bit extra to enable selling if the price drops.
  # Recommended: no less than 12 USDT. Suggested: 15 or more.
  TRADE_TOTAL: 100
  # Maximum number of trade 'slots' at any time (your USDT balance must be at least TRADE_SLOTS * TRADE_TOTAL)
  TRADE_SLOTS: 1
  # EX_PAIRS is a list of fiat currencies and margin symbols that I am excluding.
  # Anything added here will be excluded from coin withdrawal and will not be sold.
  EXCLUDE_PAIRS: ['PAX', 'EUR', 'GBP', 'JPY', 'USD', 'AUD', 'DOWN', 'UP', 'ONE', 'USDC', 'SHIB', 'VET', 'AXS', 'NEAR', 'GRT', 'CHR', 'BUSD', 'TUSD', 'LUNA', 'UST', 'BTTC', 'USDP', 'POLY']
  # define in % when to sell a coin that's not making a profit.
  STOP_LOSS: 0.5
  # define in % when to take profit on a profitable coin. default 0.25
  TAKE_PROFIT: 1
  # Use custom tickers.txt list for filtering pairs.
  # Name of custom tickers list
  CUSTOM_LIST: True
  TICKERS_LIST: 'tickers.txt'   
  # whether to use trailing stop loss or not; default is True
  # when hit TAKE_PROFIT, move STOP_LOSS to TRAILING_STOP_LOSS percentage points below TAKE_PROFIT hence locking in profit
  # when hit TAKE_PROFIT, move TAKE_PROFIT up by TRAILING_TAKE_PROFIT percentage points
  # NOTE -SELL_ON_SIGNAL_ONLY will override USE_TRAILING_STOP_LOSS
  USE_TRAILING_STOP_LOSS: False
  TRAILING_STOP_LOSS: .1
  TRAILING_TAKE_PROFIT: .1
  # Following are used to override SL, TP, TSL & TTP & SELL_ON_SIGNAL_ONLY in the case of a market crash
  # when hit SESSION_TAKE_PROFIT %, sell all coins and stop bot
  # when hit SESSION_STOP_LOSS %, sell all coins and stop bot.
  # Note, SESSION_STOP_LOSS needs to be a NEGATIVE number i.e. -2
  SESSION_TPSL_OVERRIDE: False
  SESSION_TAKE_PROFIT: 0.2
  SESSION_STOP_LOSS: -1
  # Let a signalling module control sell of coin
  # NOTE - If USE_TRAILING_STOP_LOSS: True then this needs to be False
  SELL_ON_SIGNAL_ONLY: True
  # Trading fee in % per trade.
  # If using 0.075% (using BNB for fees) you must have BNB in your account to cover trading fees.
  # If using BNB for fees, it MUST be enabled in your Binance 'Dashboard' page (checkbox).  
  TRADING_FEE: 0.075    
  #sells the percentage that is placed on it, this serves to save a part of what was purchased.
  #If get error APIError(code=-1013), change percentage 
  #sell what you bought with TRADE_TOTAL and save the profits.
  SELL_PART: False
  # Discord integration
  # Used to push alerts, messages etc to a discord channel
  MSG_DISCORD: False  
  #restart all modules every hour
  RESTART_MODULES: False  
  STATIC_MAIN_INFO: False
  DISABLE_TIMESTAMPS: True  
  SHOW_INITIAL_CONFIG: False  
  #sell the currency that was unsold so many minutes ago.(values in minutes)
  MAX_HOLDING_TIME: 0
  SHOW_TABLE_COINS_BOUGHT: True  
  SORT_TABLE_BY: "Time Held"
  REVERSE_SORT: False 
  #Enables the use of currencies with greater or lesser volume
  #This method is only compatible in ONLINE and ONLINETESNET mode
  USE_MOST_VOLUME_COINS: False
  #the list is updated every n number of minutes. by default it is updated every 24 hours (1440 minutes). 
  #Sweethackercasper's idea, thanks mate.
  UPDATE_MOST_VOLUME_COINS: 1440
  #It should not be touched here, used as record.
  VOLATILE_VOLUME: volatile_volume_17-09-2024(00_02_21)
  #idea from my psychologist, thanks Sebastian V.
  #Two different currencies can be used as a range (within the market table in Binance ordered from highest to lowest)
  #https://www.binance.com/es-AR/markets/spot_margin-USDT sort by volume
  COINS_MAX_VOLUME: BTC 
  COINS_MIN_VOLUME: TIA 
  #if the losses are equal to or greater than the established percentage, the bot will stop completely. if it is 0 it is deactivated.
  PANIC_STOP: 0
  
  SIGNALLING_MODULES:
    # NOTE: Only use the "os_xxxxxxxxx" or "nigec_xxxxxxxxx" etc signal/pause modules with this fork as 
    # the default ones WILL NOT work due to customisations for my specific purposes
    #
    - megatronmod
